spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/outfit_archive}
    username: ${SPRING_DATASOURCE_USERNAME:outfit}
    password: ${SPRING_DATASOURCE_PASSWORD:outfit}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: ${SERVER_PORT:8080}
